### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by voltagex** [PureDarwin/PureDarwin#1]
Hi,
I'm really hoping this project isn't dead - I was pointed your way by http://althenia.net/notes/darwin

Are there any plans for future development?

**Comment by vmlemon** [comment]
Hi Adam,

Right now, as you can tell by the mess, we're in something of a transitional phase (in fact, the 2nd, after we lost our original hosting arrangement with Hetzner - which is why PureDarwin.org is using Google Sites).

I decided to begin migrating the project to GitHub, from Google Code Hosting, a while ago - but since Google decided to discontinue that, we're now frantically having to find more stable hosting for things like ISOs, and other large files.

Since I'm currently away from home, I can't get you the URLs - but I've prepared a minor fix-up release of XMas (replaces the boot sector with a more-universally-compatible one), and a few minor releases were put out, unannounced (except on the mailing list), by others.

That said, the project's not dead - but does suffer a chronic lack of dedicated, full-time developers (there's folks in the IRC channel, but most of us are busy with other things, as of late), and luxuries like reliable build infrastructure (I'd say that it was ran on a shoestring - but being an informal project, there's no real "budget", for purchasing hardware, or renting time in a data centre); and we're swimming against the tide, as far as keeping in sync with new Darwin releases is concerned (and Apple haven't made things easy by alternating what they release in source, and binary form - plus, they've neglected to release some stuff in any usable form).

We do hope to release something newer than reheated builds of old Darwin 9.x releases (and we have a few components towards that goal, such as GenericPlatform, and a slightly newer X11 server) - but to do that, we'd appreciate any help that we can get. 

(You can't build Darwin under Linux, and not all of us can afford a shiny, new Intel Mac, ironically - and Hackintoshes are something of a grey area, although I'll admit that just to get things moving, I prepared that fixed XMas image in a Snow Leopard VM).

On another note, that link looks interesting. I think I might have either seen it, whilst trying to cobble together a working kernel upgrade for Darwin 8.0.1 (which is now EOL'd, and unsupported by both Apple, and the PureDarwin project), a few years ago.

In the meantime, I hope that sheds some light on the state of play.

Tyson.
Sent from my BlackBerry® smartphone on O2

-----Original Message-----

**Comment by voltagex** [comment]
Many thanks for the update.

It might be worth approaching Rackspace for hosting -
http://blog.rtwilson.com/review-rackspace-cloud-free-open-source-project-hosting/
although I'm not sure that particular person is still at Rackspace.

For Mac access, perhaps one of the companies that provides Mac colo
facilities?

Happy to email on your behalf - I have extra free time for a while.

**Comment by vmlemon** [comment]
No worries. 

Please feel free to try, anyway - I guess that it'd provide a huge boost, if they were able to help; but at the same time, it's another organisation to worry about, if things go wrong (although my experiences with JungleDisk have been excellent, to date).

For what it's worth, I think there was some kind of "cloud hosting" service for Mac OS X - but I haven't investigated the costs, or level of access, yet.
Sent from my BlackBerry® smartphone on O2

-----Original Message-----

**Comment by IRTermite** [comment]
Greetings,
I am the Racker who responded to your tweet asking about this project. (https://twitter.com/Rackspace/status/618415702391717888) Time for the >140 character response... I am currently not aware of any educational programs we are running, like the above mentioned $2000/mo discount. Currently, we have a $50/mo Developer+ Program, and a Startup Program rate (forget what that discount was). Both have expirations, and won't cover more than 1-2 years worth of hosting. They are intended to get you off the ground and running. I see you are hosting the code in GitHub, which is free for open code, and relatively cheap for private repos; so that's a good start. What are the extra bits that you need to cover? The ISOs and other storage? Anything else? I will look around for what I can find, and try and assist.

**Comment by IRTermite** [comment]
@jessenoller (jnoller on github) just replied to my tweet. Give him a shout; he runs our OSS program.

**Comment by vmlemon** [comment]
Thanks for the pointer, @IRTermite

**Comment by voltagex** [comment]
@vmlemon If you send me the details of what kind of hosting is required (or post them here) , I will email Jesse.

**Comment by mdaniel** [comment]
>  find more stable hosting for things like ISOs, and other large files.

The Racker in the tweet hinted at it, but it is my understanding that when a project [makes a release](https://developer.github.com/v3/repos/releases/#create-a-release) then from that point forward one can [upload a binary asset](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) that is attached to the release. The only restriction that I am aware of is that [each file must be under 2GB](https://help.github.com/articles/distributing-large-binaries/) which is unlikely to affect PureDarwin for a while.

> reliable build infrastructure

FWIW, Travis-CI claims that they offer [OSX build environments](http://docs.travis-ci.com/user/workers/os-x-infrastructure/), and as icing on the cake they will even ship the binaries up as [GitHub releases](http://docs.travis-ci.com/user/deployment/releases/) (for tags only, logically)

> not all of us can afford a shiny, new Intel Mac

I take it from your spelling of centre and O2 in your sig that you're in the UK, but here in America one can obtain a [Mac Mini](http://www.ebay.com/itm/Apple-Mac-Mini-2009-MB463LL-A-A1283-2-0GHz-Intel-Core-2-Duo-2GB-120GB-Yosemite-/141702203904) for what I consider peanuts [roughly the [same](http://www.ebay.co.uk/itm/Apple-Mac-Mini-Desktop-Server-MC438B-A-June-2010-/331597724589) in the UK, but it's hard for me to judge whether that is expensive or not]. I personally have a [Mac Pro](http://www.ebay.com/itm/Apple-Mac-Pro-A1186-2-66-GHz-D-Core-Xeon-5150-x1-8GB-500GB-HD-OS-10-7-/252019386464) that I got off eBay (I wish I had only paid $180; mine was $300) and then I packed it full of RAM and an SSD and love it to death. Now I would never advocate shipping a Mac Pro overseas, but - customs and duties dumbness aside - I would gladly pay $180 to have a modern, open source, working Darwin for the masses. I have spent more than that on [Kickstarter](https://www.kickstarter.com/profile/mdaniel) and don't see this effort as terribly different.

**Comment by voltagex** [comment]
I'm willing to go halves on buying a Mac Mini off eBay but there is a
viable solution in issue #2, as well.

**Comment by voltagex** [comment]
Ooh, I will look at Travis-CI this afternoon too. Could I please be added
to the project as a contributor, @vmlemon?

**Comment by vmlemon** [comment]
Sure - I think I just need an e-mail address, in order to do that.
Sent from my BlackBerry® smartphone on O2

-----Original Message-----

**Comment by voltagex** [comment]
Ping me in IRC

**Comment by vmlemon** [comment]
Aah, added your username (voltagex) as an "Owner"

**Comment by vmlemon** [comment]
Haven't looked at Travis in depth - but I don't know if we'd be able to use DarwinBuild there (we don't keep the full OS source code in our repository - just a bunch of delta patches, and additional components, that get applied when downloading the code directly from Apple's Open Source site), and unless things have changed, there was a limit on how long a build can run for, before it gets killed.

**Comment by voltagex** [comment]
I'd say we could ask nicely for the time limit to be increased. You have to enable Travis per repo though. Maybe we should create a smaller repo with a Mac-only component as a proof of concept first?

I'm going to take this out to another issue, if that's OK - this one's got a lot of different topics going on.

**Comment by vmlemon** [comment]
Sure - feel free.

**Comment by hideout** [comment]
@tyson did you ever played with Travis?

and yes Adam would be cool if you could give us a little introduction to
travis-ci.

cheers

ferdinand

2015-07-08 9:54 GMT+02:00 Tyson Key <notifications@github.com>:

**Comment by vmlemon** [comment]
I had a look at their Website, but I haven't actually played with the tool itself, before. It does seem interesting, and potentially useful, though.

**Comment by hideout** [comment]
indeed and facebook and twitter use it too!

So i think its fine for puredarwin too! ;))

2015-07-08 9:59 GMT+02:00 Tyson Key <notifications@github.com>:
