### ISSUE TITLE
ld64: really ignore -(no_)adhoc_codesign?

### ISSUE THREAD

**Issue by asdfugil** [PureDarwin/PureDarwin#100]
ld64 is used for cross compiling for other Darwin platforms as well, so it isn't only used on apple silicon PureDarwin builds (which doesn't exist).

Additionally, I cannot see anything wrong with code verification as long as it does not restrict the code that could be run by the user.

I do not see the necessity of the patch, and the less patches there is, the less maintenance work is needed.

**Comment by wjk** [comment]
Xcode always passes this flag to ld, and there’s no way to stop it. We use `-fuse-ld=` to have clang run a locally built copy of ld because I wanted our build to be self-contained. This ld died of an unrecognized-parameter error due to these flags, which is why I added the code to ignore it. Even though we don’t currently support Xcode, as soon as I get the source code organization figured out, I will re-enable Xcode support in CMake. (Or someone else can do it. That’s fine too!) This change will become required at that time. Thanks!
