### ISSUE TITLE
I think you can suggest Apple to reopen the OpenDarwin project.

### ISSUE THREAD

**Issue by ghost** [PureDarwin/PureDarwin#117]
Now that the Mac is using Apple Silicon as its processor, running a Darwin-based operating system on an x86 platform will not negatively impact Apple, so you can suggest that Apple reopen the OpenDarwin project.

**Comment by njlyf2011** [comment]
The Hackintosh community has produced a lot of legitimate and useful results over the years. I think reopening the OpenDarwin project will turn it into a great operating system.

**Comment by willzyx-hub** [comment]
> The Hackintosh community has produced a lot of legitimate and useful results over the years. I think reopening the OpenDarwin project will turn it into a great operating system.

But How ? i don't think Apple gonna respond if you send an Email to their Email Addresses

**Comment by LuNeder** [comment]
That would be awesome!

> running a Darwin-based operating system on an x86 platform will not negatively impact Apple

I do not think running a Darwin-based operating system on any platform, even arm, would negatively impact Apple. The intention behind OpenDarwin and PureDarwin were never to substitute macs or macOS.

I also do not believe that apple making macOS itself more open would impact them negatively. Hackintoshes already exist, and this won’t change no matter the ‘openness’ of mac. Even so, the reason no company **sells** hackingtoshed computers out there is that Apple could sue them. Even if macOS was made completely open source, they would not be negatively impacted for as long as they kept in the license that only Apple can sell computers running macOS.
People who buy macs do not buy them only because of the OS, and the Apple special focus would always be on macs so the OS would always run better on their computers anyway - even if hackingtoshes got better drivers and stuff from the community. But anyway, OpenDarwin wouldn’t even do that - that would only be the case if they open sourced macOS itself.


That said, Darwin is a separate system that is purely the base for macOS. Realistically, even **if** OpenDarwin were ever able to run programs made for macOS it would never substitute macOS - it’s not even its goal.

Apple has a perfectly safe position for bringing OpenDarwin back, and that’d be super cool!

**Comment by wjk** [comment]
Yeah, this will never fly. They’re probably so sick of these requests by now that they delete them as soon as they’re received. There is absolutely no financial reason why Apple would ever want to do this, and that’s the only reason that matters. A great amount of their platform security is based upon the fact that we don’t know how it works. Furthermore, the move to Apple silicon gives them even more reason to keep their source code under lock and key, as they have secrets in the hardware now, too. Look at Asahi Linux; they were never able to initialize the graphics card on their machines, because it is cryptographically locked to only talk to Apple software. The only thing Apple is interested in is secrecy. They are so secretive that developers aren’t even allowed to read bug reports; they are always rewritten by someone else first.

Please stop opening these kinds of issues.
