### ISSUE TITLE
Want to bring back darwinbuild

### ISSUE THREAD

**Issue by csekel** [PureDarwin/PureDarwin#149]
@wjk I would like to bring darwinbuild out of archive and start working on it for when we can build PureDarwin on PureDarwin. 

Do you have any issues with this? I'd also merge in your last PR to the project it's some great work to build onto.

**Comment by csekel** [comment]
I will be the maintainer of the project too.

**Comment by wjk** [comment]
@csekel I don’t know if darwinbuild work would if brought back because Apple no longer hosts the open-source packages on their website. You must now clone a repo from GitHub and switch to a specific tag. Nevertheless, you are free to try. I have removed the archive flag from the darwinbuild repo.

**Comment by wjk** [comment]
Some more notes:

opensource.apple.com no longer hosts the source tarballs. The “download tarball” link on their website now redirects to a GitHub release. We will need to completely rewrite how darwinbuild locates source tarballs for this to work, because the URL patterns are completely different.

I decided to move to CMake because darwinbuild when I last used it did not work with the edit-run-debug developer flow very well. I could not simply apply changes and build; I had to distill all the changes into a patch, put the patch into the `Sources` directory, add the patch to the darwinbuild plist, and reinitialize darwinbuild. If we were to move back to darwinbuild, I would need a better way to do edit-run-debug builds.

Does this also mean we also move back to Xcode? If use use xcodeproj for our build system, we will need to figure out how to make Xcode look at our distribution first, before Apple’s SDK. [There is a build setting](https://developer.apple.com/documentation/xcode/build-settings-reference#Additional-SDKs) that supposedly does this, but the last time I tried it (many Xcode versions ago), it didn’t do anything. Another reason I hated using Xcode was that there was no good way to get Xcode to link against the proper dependencies when used with darwinbuild and when used in the GUI.

However, all that being said, if we decide to go back to darwinbuild and one repository per component like we used to, I can strip all the code out of this repo, put them in repos under the PureDarwin org, and add a script to the main repo that will invoke darwinbuild as many times as are needed. In all honesty, this would work better in the long term, as big monorepos are a pain to work with. (Darling uses submodules extensively to combat this problem, but I won’t touch them, because they make it impossible to fork darling to submit a PR.)

**Comment by csekel** [comment]
Completely understood and these are some of the changes/logic I want to fix as well. You keep going down the path you're doing now with c make and no don't want to re breakout repos again. I will go over the darwinbuild repo and come up with a road-map to bring darwinbuild into our way of wanting it do things. I don't want xcode either trust me, unless they(Apple) opensource it but that is never going to happen lol..

**Comment by LukeUsher** [comment]
I did some playing around with darwinbuild not too long ago and I noticed that the old tarball urls are still hosted: apple are automatically redirecting the opensource.apple.com tarball urls to the github tarball urls; the download aspect still works as of April 2024 when I last checked.

There are still some issues with actually extracting the tarballs, however, because the resulting folder names after unpacking are different; an ugly (but working) solution for this I hacked together was the following:

```
	# Apple's transition to Github caused directory names to be incorrect, we need to fix this (eg xnu-x.x.x becomes xnu-xnu-x.x.x)
if [ -d "$SRCROOT/../$projnam-$project" ]; then
    cp -R "$SRCROOT/../$projnam-$project/" "$SRCROOT"
    rm -rf "$SRCROOT/../$projnam-$project"
fi
```

**Comment by csekel** [comment]
Thanks for the info and insight there!
