### ISSUE TITLE
Can I run PureDarwin on a Mac?

### ISSUE THREAD

**Issue by Amazeryogo** [PureDarwin/PureDarwin#60]
So I have a  Macbook Air from 2011 and It barely works after I updated it to High Sierra, 3 years ago, So I had a question, Can I run PureDarwin on the Mac after completely erasing OS X and using PureDarwin as a fresh install?

**Comment by wjk** [comment]
At this point, the development version of PureDarwin doesn't even boot. The [“old” version](https://github.com/PureDarwin/PD-17.4-Beta) will boot in QEMU, but don't even think of trying it on a real Mac, because PureDarwin lacks the required kext support for standard hardware buses — not to mention Apple’s proprietary devices. (Furthermore, the old beta is missing most userland features, including network support, even in QEMU.) Sorry about that!

**Comment by Amazeryogo** [comment]
No problem , i was just curious
